spilo:

  replicaCount: 2

  continuousArchive:
    enabled: true
    scheduleCronJob: "0 2 * * *"
    retainBackups: 3
    storage: s3
    s3:
      bucket: itvrdv
      secretName: itvr-db-backup-s3

  persistentVolume:
    size: 700Mi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 120m
      memory: 400Mi
    requests:
      cpu: 60m
      memory: 200Mi  

  podDisruptionBudget:
    enabled: false

  probes:
    liveness:
      enabled: false
    readiness:
      enabled: true 
      initialDelaySeconds: 90
      failureThreshold: 20         