spilo:

  replicaCount: 2

  continuousArchive:
    scheduleCronJob: "*/10 * * * *"
    pvc:
      storageClass: netapp-file-backup
      size: 300Mi  

  persistentVolume:
    size: 150Mi
    storageClass: netapp-block-standard

  resources:
    limits:
      cpu: 60m
      memory: 200Mi
    requests:
      cpu: 30m
      memory: 100Mi  