kind: Secret
apiVersion: v1
metadata:
  name: {{ include "itvr-backend.django-secret" . }}
  creationTimestamp: null
  labels:
    {{- include "itvr-backend.labels" . | nindent 4 }}  
data:
  DJANGO_SECRET_KEY: {{ include "itvr-backend.djangoSecretKey" . }}
type: Opaque
