apiVersion: v1
kind: Service
metadata:
  name: {{ include "itvr-backend.serviceName" . }}
  labels:
    {{- include "itvr-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: backend
  selector:
    {{- include "itvr-backend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
