apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-minio-secret
parameters:
  - name: ENV
    description: env name, dev, test or prod
    required: true
  - name: ROOT_USER
    required: true
  - name: ROOT_PASSWORD
    description: Minio secret key
    from: "[a-zA-Z0-9]{8}"
    generate: expression
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: itvr-minio-${ENV}
    stringData:
      root-user: ${ROOT_USER}
      root-password: ${ROOT_PASSWORD}
