apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-cra-secret
parameters:
  - name: EPF_PASSWORD
    description: EPF password for CRA
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: itvr-cra-secret
    stringData:
      EPF_PASSWORD: ${EPF_PASSWORD}
