apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-cra-secret
parameters:
  - name: ENV
    description: ENV
    required: true
  - name: CRA_CERTIFICATE
    description: CRA_CERTIFICATE
    required: true
  - name: CRA_CERTIFICATE_CRL_DN
    description: CRA_CERTIFICATE_CRL_DN
    required: true
  - name: EPF_FILENAME
    description: EPF_FILENAME
    required: true
  - name: EPF_PASSWORD
    description: EPF password for CRA
    required: true
  - name: DIRECTORY_IP
    description: DIRECTORY_IP
    required: true
  - name: DIRECTORY_PORT
    description: DIRECTORY_PORT
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: itvr-cra-${ENV}
    stringData:
      CRA_CERTIFICATE: ${CRA_CERTIFICATE}
      CRA_CERTIFICATE_CRL_DN: ${CRA_CERTIFICATE_CRL_DN}
      EPF_FILENAME: ${EPF_FILENAME}
      EPF_PASSWORD: ${EPF_PASSWORD}
      DIRECTORY_IP: ${DIRECTORY_IP}
      DIRECTORY_PORT: ${DIRECTORY_PORT}
