# Stage 1: Use yarn to build the app
FROM artifacts.developer.gov.bc.ca/docker-remote/node:16 as builder
ENV NODE_ENV=production
WORKDIR /usr/src/app
COPY ./ ./
RUN npm install --production
RUN npm run build

# Stage 2: Copy the JS React SPA into the Nginx HTML directory
FROM artifacts.developer.gov.bc.ca/docker-remote/bitnami/nginx:1.21.6
USER root
RUN apt-get install vim -y
COPY --from=builder /usr/src/app/build /app
USER 1001
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
