# Generated by Django 4.0.1 on 2022-06-24 18:18

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='application_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='consent_personal',
            field=models.BooleanField(null=True, validators=[api.validators.validate_consent]),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='consent_tax',
            field=models.BooleanField(null=True, validators=[api.validators.validate_consent]),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[api.validators.validate_driving_age]),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='sin',
            field=encrypted_fields.fields.EncryptedCharField(max_length=9, null=True, validators=[api.validators.validate_sin]),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='tax_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
