# Generated by Django 4.0.1 on 2022-03-21 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeVerificationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('img', models.ImageField(upload_to='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incomeverification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
