# Generated by Django 4.0.1 on 2022-04-12 22:18

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='application_type',
            field=models.CharField(default='individual', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='spouse_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_user', models.CharField(default='SYSTEM', max_length=130)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('update_user', models.CharField(max_length=130, null=True)),
                ('sin', encrypted_fields.fields.EncryptedCharField(max_length=9)),
                ('last_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_names', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('doc1', models.ImageField(upload_to='docs')),
                ('doc2', models.ImageField(upload_to='docs')),
                ('verified', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.goelectricrebateapplication')),
            ],
            options={
                'db_table': 'household_member',
            },
        ),
    ]
