# Generated by Django 4.0.1 on 2022-04-26 19:20
# Increment sequence to a certain number.
# 

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "create sequence api_cra_wage_request_id_seq start with 1 increment by 1 minvalue 1"
        )
    ]
