# Generated by Django 4.0.1 on 2022-06-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebate',
            name='ncda_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
