# Generated by Django 4.0.1 on 2022-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_goelectricrebateapplication_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='is_legacy',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('user__isnull', False), _connector='OR'), name='user_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('sin__isnull', False), _connector='OR'), name='sin_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('last_name__isnull', False), _connector='OR'), name='last_name_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('first_name__isnull', False), _connector='OR'), name='first_name_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('email__isnull', False), _connector='OR'), name='email_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('address__isnull', False), _connector='OR'), name='address_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('city__isnull', False), _connector='OR'), name='city_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('date_of_birth__isnull', False), _connector='OR'), name='date_of_birth_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('tax_year__isnull', False), _connector='OR'), name='tax_year_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('consent_personal__isnull', False), _connector='OR'), name='consent_personal_null_constraint'),
        ),
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('consent_tax__isnull', False), _connector='OR'), name='consent_tax_null_constraint'),
        ),
    ]
