# Generated by Django 4.0.1 on 2022-07-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goelectricrebateapplication_is_legacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='status',
            field=models.CharField(choices=[('household_initiated', 'Household Initiated'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('declined', 'Declined'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=250),
        ),
    ]
