# Generated by Django 4.0.1 on 2022-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_goelectricrebateapplication_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goelectricrebateapplication',
            constraint=models.CheckConstraint(check=models.Q(('is_legacy__exact', True), ('application_type__isnull', False), _connector='OR'), name='application_type_null_constraint'),
        ),
    ]
