# Generated by Django 4.0.1 on 2022-07-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_goelectricrebateapplication_application_type_null_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiatedGoElectricRebateApplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.goelectricrebateapplication',),
        ),
    ]
