# Generated by Django 4.0.1 on 2022-07-12 21:56

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initiatedgoelectricrebateapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goelectricrebate',
            options={},
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='doc1',
            field=models.ImageField(blank=True, null=True, upload_to='docs', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='doc2',
            field=models.ImageField(blank=True, null=True, upload_to='docs', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='doc1',
            field=models.ImageField(blank=True, null=True, upload_to='docs', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='doc2',
            field=models.ImageField(blank=True, null=True, upload_to='docs', validators=[api.validators.validate_file_size]),
        ),
        migrations.AlterModelTable(
            name='goelectricrebate',
            table='go_electric_rebate',
        ),
    ]
