# Generated by Django 4.0.1 on 2022-08-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_goelectricrebateapplication_doc1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InitiatedGoElectricRebateApplication',
        ),
        migrations.CreateModel(
            name='CancellableGoElectricRebateApplication',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.goelectricrebateapplication',),
        ),
        migrations.CreateModel(
            name='SearchableGoElectricRebateApplication',
            fields=[
            ],
            options={
                'ordering': ['-modified'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.goelectricrebateapplication',),
        ),
    ]
