# Generated by Django 4.0.1 on 2022-08-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_initiatedgoelectricrebateapplication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancellablegoelectricrebateapplication',
            options={'ordering': ['-modified']},
        ),
        migrations.AlterModelOptions(
            name='submittedgoelectricrebateapplication',
            options={'ordering': ['-modified']},
        ),
    ]
