# Generated by Django 4.0.1 on 2022-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_goelectricrebateapplicationwithfailedemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='reason_for_decline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
