# Generated by Django 4.0.1 on 2022-10-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_goelectricrebateapplication_reason_for_decline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='confirmation_email_success',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='spouse_email_success',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
