# Generated by Django 4.0.8 on 2022-12-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_goelectricrebateapplication_confirmation_email_success_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='status',
            field=models.CharField(choices=[('household_initiated', 'Household Initiated'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('declined', 'Declined'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('not_approved_sin_mismatch', 'Not Approved - SIN Mismatch'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=250),
        ),
    ]
