# Generated by Django 4.0.8 on 2023-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_goelectricrebateapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='approved_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='not_approved_on',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='created',
            field=models.DateTimeField(verbose_name='submitted on'),
        ),
    ]
