# Generated by Django 4.0.8 on 2023-01-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_goelectricrebateapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='approved_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='not_approved_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
