# Generated by Django 4.0.8 on 2023-01-25 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_goelectricrebateapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goelectricrebateapplication',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
