# Generated by Django 4.0.8 on 2023-01-31 17:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_goelectricrebateapplication_approved_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
