# Generated by Django 4.0.9 on 2023-02-23 23:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_goelectricrebateapplication_approved_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicenceEditableGoElectricRebateApplication',
            fields=[
            ],
            options={
                'ordering': ['-modified'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.goelectricrebateapplication',),
        ),
        migrations.CreateModel(
            name='DriverLicenceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('drivers_licence', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(7)])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.goelectricrebateapplication')),
            ],
            options={
                'db_table': 'driver_licence_history',
            },
        ),
    ]
