# Generated by Django 4.0.9 on 2023-04-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_driverlicenceeditablegoelectricrebateapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='status',
            field=models.CharField(choices=[('household_initiated', 'Household Initiated'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('declined', 'Declined'), ('approved', 'Approved'), ('not_approved_high_income', 'Not Approved - High Income'), ('not_approved_no_cra_info', 'Not Approved - No CRA Info'), ('not_approved_sin_mismatch', 'Not Approved - SIN Mismatch'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=250),
        ),
    ]
