# Generated by Django 4.0.9 on 2024-05-29 22:39

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_changeredeemedgoelectricrebateapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goelectricrebateapplication',
            name='drivers_licence',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(7), api.validators.validate_drivers_licence]),
        ),
    ]
