# Generated by Django 4.0.9 on 2024-06-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_goelectricrebateapplication_drivers_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredGoElectricRebateApplication',
            fields=[
            ],
            options={
                'ordering': ['-modified'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.goelectricrebateapplication',),
        ),
    ]
