apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "itvr-cra.fullname" . }}
  labels:
    {{- include "itvr-cra.labels" . | nindent 4 }}
spec:
  host: {{ include "itvr-cra.fullname" . }}.apps.silver.devops.gov.bc.ca
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "itvr-cra.fullname" . }}
    weight: 100
  wildcardPolicy: None