apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: allow-backend-accepts
parameters:
  - name: ENV
    displayName: null
    description: such as dev, test or prod
    required: true
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-backend-accepts-${ENV}
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: itvr-backend-${ENV}
          app.kubernetes.io/name: itvr-backend
      ingress:
        - ports:
            - protocol: TCP
              port: 8080
          from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: itvr-frontend-${ENV}
                  app.kubernetes.io/name: itvr-frontend
      policyTypes:
        - Ingress
