apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: allow-spilo-accepts
parameters:
  - name: ENV
    displayName: null
    description: such as dev, test or prod
    required: true
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-spilo-accepts-${ENV}
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: itvr-spilo
          app.kubernetes.io/name: spilo
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: itvr-spilo
                  app.kubernetes.io/name: spilo
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: itvr-backend-${ENV}
                  app.kubernetes.io/name: itvr-backend
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  openshift.io/deployer-pod.type: hook-mid
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: itvr-task-queue-${ENV}
                  app.kubernetes.io/name: crunchy-postgres
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - podSelector:
                matchLabels:
                  cronjob: itvr-db-backup
        - ports:
            - protocol: TCP
              port: 5432
          from:
            - namespaceSelector:
                matchLabels:
                  environment: ${ENV}
                  name: 30b186
            - podSelector:
                matchLabels:
                  app: metabase
      policyTypes:
        - Ingress
