apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: allow-minio-accepts
parameters:
  - name: ENV
    displayName: null
    description: such as dev, test or prod
    required: true
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-minio-accepts-${ENV}
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: itvr-minio-${ENV}
          app.kubernetes.io/name: minio
      ingress:
        - ports:
            - protocol: TCP
              port: 9000
          from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: itvr-cra-${ENV}
                  app.kubernetes.io/name: itvr-cra
      policyTypes:
        - Ingress
