patroni:

  replicaCount: 1

  resources:
    # If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 60m
      memory: 160Mi
    requests:
       cpu: 30m
       memory: 80Mi

  persistentVolume:
    size: 250Mi