apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cas-cif.fullname" . }}-deploy-data
  labels: {{ include "cas-cif.labels" . | nindent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels: {{ include "cas-cif.labels" . | nindent 14 }}
        spec:
          activeDeadlineSeconds: 600
          restartPolicy: Never
          containers:
            - env:
                - name: SQITCH_TARGET
                  value: "db:pg:"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: database-owner-user
                      name: {{ template "cas-cif.fullname" . }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-owner-password
                      name: {{ template "cas-cif.fullname" . }}
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: {{ template "cas-cif.fullname" . }}
                - name: PGPORT
                  value: "5432"
                - name: PGHOST
                  value: {{ template "cas-cif.fullname" . }}-patroni
                - name: SQITCH_FULLNAME
                  value: OpenShift Deployer
                - name: SQITCH_EMAIL
                  value: deployer@pathfinder.gov.bc.ca
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
              name: {{ template "cas-cif.fullname" . }}-schema-deploy-data
              image: {{ .Values.image.schema.repository }}:{{ default .Values.defaultImageTag .Values.image.schema.tag }}
              imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.schema.pullPolicy }}
              resources:
                limits:
                  cpu: 500m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euo pipefail;
                  sqitch deploy;
                  if [[ "$NAMESPACE" == *-dev  ]]; then
                  for file in data/dev/*.sql; do
                    psql -d cif -f "${file}";
                  done;
                  fi;
