kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: clamav-signature-db
  labels: {{ include "itvr-clamav.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard

