apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-dotnet-core-bc
parameters:
  - name: NAME
    value: itvr
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is itvr
    required: true
  - name: GIT_URL
    value: https://github.com/bcgov/itvr.git
    displayName:
    description: itvr repo
    required: true
  - name: GIT_REF
    value: dotnet-0.1.0
    displayName:
    description: itvr branch name of the pr
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the dotnet-core image
      labels:
        shared: "true"
      creationTimestamp: null
      name: ${NAME}-dotnet-core
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        description: Defines how to build the application
      creationTimestamp: null
      name: ${NAME}-dotnet-core
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-dotnet-core:0.1.0
      postCommit: {}
      resources:
        limits:
          cpu: 200m
          memory: 300Mi
        requests:
          cpu: 100m
          memory: 100Mi
      runPolicy: SerialLatestOnly
      source:
        contextDir: openshift/templates/dotnet-core/docker
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        type: Git
      strategy:
        dockerStrategy:
          env:
          - name: CRA_KEY
            value: testvalue
          forcePull: true
          noCache: true
        type: Docker
      triggers:
      - imageChange: {}
        type: ImageChange
      - type: ConfigChange
    status:
      lastVersion: 0