apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-backend-dc
parameters:
  - name: ENV_NAME
    value: dev
    displayName: Environment name
    description: 'Environment name, dev, test and prod'
    required: true
  - name: CPU_REQUEST
    value: 20m
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    value: 50m
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    value: 100Mi
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    value: 200Mi
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: PVC_SIZE
    value: 100Mi
    displayName: nagios pvc size
    description: nagios pvc size
    required: true    
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: itvr-dotnet-core
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-file-standard
      template.openshift.io.bcgov/create: 'true'
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: ${PVC_SIZE}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    creationTimestamp: null
    name: itvr-dotnet-core
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: itvr-dotnet-core
    strategy:
      activeDeadlineSeconds: 800
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: itvr-dotnet-core
      spec:
        containers:
          - name: itvr-dotnet-core
            image: null
            imagePullPolicy: IfNotPresent
            env: null
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - pwd
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 3                
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - itvr-dotnet-core
          from:
            kind: ImageStreamTag
            name: itvr-dotnet-core:0.1.0
            namespace: ac294c-tools
          lastTriggeredImage: null
        type: ImageChange
      - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
