apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-dotnet-core-bc
parameters:
  - name: GIT_URL
    value: https://github.com/bcgov/itvr.git
    displayName:
    description: itvr repo
    required: true
  - name: GIT_REF
    value: dotnet-0.1.0
    displayName:
    description: itvr branch name of the pr
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the dotnet-core image
      labels:
        shared: "true"
      creationTimestamp: null
      name: itvr-dotnet-core
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        description: Defines how to build the application
      creationTimestamp: null
      name: itvr-dotnet-core
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: itvr-dotnet-core:0.1.0
      resources:
        limits:
          cpu: 400m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 250Mi          
      postCommit: {}
      runPolicy: SerialLatestOnly
      source:
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        type: Git
        contextDir: dotnet
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: dotnet-60:6.0-5
            namespace: ac294c-tools
          forcePull: true
          noCache: true      
          env:
            - name: DOTNET_ASSEMBLY_NAME
              value: pscoretest      
      type: Source
      triggers:
      - imageChange: {}
        type: ImageChange
      - type: ConfigChange
    status:
      lastVersion: 0