kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "itvr-frontend.configmapName" . }}
  labels:
    {{- include "itvr-frontend.labels" . | nindent 4 }}
data:
  features.js: |
    window.itvr_config = {
      "REACT_APP_BCSC_KEYCLOAK_CLIENT_ID": "{{ .Values.frontend.reactAppBCSCKeycloakClientId }}",
      "REACT_APP_BCSC_KEYCLOAK_REALM": "{{ .Values.frontend.reactAppBCSCKeycloakRealm }}",
      "REACT_APP_BCSC_KEYCLOAK_URL": "{{ .Values.frontend.reactAppBCSCKeycloakUrl }}",
      "REACT_APP_BCEID_KEYCLOAK_CLIENT_ID": "{{ .Values.frontend.reactAppBCeIDKeycloakClientId }}",
      "REACT_APP_BCEID_KEYCLOAK_REALM": "{{ .Values.frontend.reactAppBCeIDKeycloakRealm }}",
      "REACT_APP_BCEID_KEYCLOAK_URL": "{{ .Values.frontend.reactAppBCeIDKeycloakUrl }}",
      "REACT_APP_API_BASE": "https://itvr-backend{{ .Values.suffix }}.apps.silver.devops.gov.bc.ca",
      "REACT_APP_ENV": "{{ .Values.envName }}",
      "SNOWPLOW_COLLECTOR": "{{ .Values.snowplowCollector }}" };
