apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    {{- include "itvr-frontend.labels" . | nindent 4 }}  
  creationTimestamp: null
  name: {{ include "itvr-frontend.imagestreamName" . }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: {{ .Values.imageEnv.tag }}
      from:
        kind: ImageStreamImage
        namespace: {{ .Values.toolsNamespace }}
        name: {{ .Values.imageTools.tag }}
      importPolicy: {}
      referencePolicy:
        type: Local
