apiVersion: v1
kind: Service
metadata:
  name: {{ include "itvr-frontend.serviceName" . }}
  labels:
    {{- include "itvr-frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    {{- include "itvr-frontend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
