apiVersion: v1
kind: Service
metadata:
  name: {{ include "itvr-frontend.serviceName" . }}
  labels:
    {{- include "itvr-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: web
  selector:
    {{- include "itvr-frontend.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
