kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: itvr-minio-dev
spec:
  host: itvr-minio-dev.apps.silver.devops.gov.bc.ca
  to:
    kind: Service
    name: itvr-minio
    weight: 100
  port:
    targetPort: minio-api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
