kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.minio.routeName }}
spec:
  host: {{ .Values.minio.hostName }}
  to:
    kind: Service
    name: itvr-minio
    weight: 100
  port:
    targetPort: minio-api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
