apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
  creationTimestamp: null
  name: {{ include "itvr-taskq.deploymentconfigName" . }}
  labels:
    {{- include "itvr-taskq.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    {{- include "itvr-taskq.selectorLabels" . | nindent 4 }}
  strategy:
    activeDeadlineSeconds: 800
    recreateParams:
      mid:
        execNewPod:
          command:
            - /bin/sh
            - '-c'
            - |-
              sleep 60
              python ./manage.py migrate
              python ./manage.py createcachetable
          containerName: task-queue
        failurePolicy: Retry
      timeoutSeconds: 600
    resources: {}
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "itvr-taskq.labels" . | nindent 8 }}
    spec:
      containers:
        - name: task-queue
          image: null
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: DB_HOST
              value: itvr-spilo
            - name: DB_HOST_READONLY
              value: itvr-spilo-readonly
            - name: DB_NAME
              value: itvr
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: itvr-patroni-app
                  key: app-db-password
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: itvr-patroni-app
                  key: app-db-username
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "itvr-taskq.django-secret" . }}
                  key: DJANGO_SECRET_KEY      
            - name: DJANGO_SALT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "itvr-taskq.django-salt" . }}
                  key: DJANGO_SALT_KEY
            - name: EMAIL_SERVICE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: itvr-email-service
                  key: EMAIL_SERVICE_CLIENT_ID                      
            - name: EMAIL_SERVICE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: itvr-email-service
                  key: EMAIL_SERVICE_CLIENT_SECRET
            - name: CHES_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: itvr-email-service
                  key: CHES_AUTH_URL                      
            - name: CHES_EMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: itvr-email-service
                  key: CHES_EMAIL_URL
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: itvr-email-service
                  key: SENDER_EMAIL      
            - name: SENDER_NAME
              valueFrom:
                secretKeyRef:
                  name: itvr-email-service
                  key: SENDER_NAME
            - name: SEND_EMAIL
              value: '{{ .Values.taskq.sendEmail }}'
            - name: DJANGO_DEBUG
              value: '{{ .Values.taskq.djangoDebug }}'
            - name: DJANGO_TASKS
              value: 'true'
            - name: CORS_ORIGIN_WHITELIST
              value: {{ .Values.taskq.corsOriginWhitlist }}    
            - name: NCDA_CLIENT_ID
              valueFrom:
                secretKeyRef: 
                  name: itvr-ncda
                  key: NCDA_CLIENT_ID
            - name: NCDA_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: itvr-ncda
                  key: NCDA_CLIENT_SECRET
            - name: NCDA_RESOURCE
              valueFrom:
                secretKeyRef:
                  name: itvr-ncda
                  key: NCDA_RESOURCE
            - name: NCDA_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: itvr-ncda
                  key: NCDA_AUTH_URL
            - name: NCDA_SHAREPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: itvr-ncda
                  key: NCDA_SHAREPOINT_URL                     
            - name: CRA_ENVIRONMENT
              value: {{ .Values.taskq.craEnvrionment }}
            - name: RUN_JOBS
              value: 'true'                                  
          readinessProbe:  
            exec:
              command:
                - /bin/bash
                - '-c'
                - ls -l
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 120m
              memory: 400Mi
            requests:
              cpu: 60m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - task-queue
        from:
          kind: ImageStreamTag
          namespace: {{ .Values.image.namespace }}
          name: {{ include "itvr-taskq.fullname" . }}:{{ .Values.imageEnv.tag }}
        lastTriggeredImage: null
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
