app:
  sitewide_notice:
    content: <div class="alert alert-warning">This is the DEV environment.</div>

cas-postgres:
  patroni:
    walE:
      enable: true
      # the GCS bucket name should be {{ namespace }}-{{ gcs.bucketSuffix }}
      gcsBucket: 0ab226-dev-cif-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-0ab226-dev-cif-backups-service-account-key # pragma: allowlist secret
    # options below are required if walE.enable is true
  namespace: 0ab226-dev
  gcs:
    bucketSuffix: cif-backups

db:
  preInitCommand: |
    psql<<EOF
      select pg_terminate_backend(pid) from pg_stat_activity where
      -- don't kill my own connection!
      pid <> pg_backend_pid()
      -- don't kill the connections to other databases
      and datname = '$(CIF_DATABASE)';
      drop database if exists $(CIF_DATABASE);
      drop user if exists $(CIF_USER);
    EOF

