apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: metabase-dc
parameters:
  - name: ENV_NAME
    value: 
    required: true
  - name: METABASE_PVC_SIZE
    value: 
    required: true    
  - name: CPU_REQUEST
    value: 50Mi
    displayName: Requested CPU
    description: Requested CPU
    required: true    
  - name: CPU_LIMIT
    value: 200Mi
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    value: 50Mi
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    value: 200Mi
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: metabase
    labels:
      app: metabase
      service: metabase
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: metabase
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-file-standard
      template.openshift.io.bcgov/create: 'true'
    labels:
      app: metabase
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: ${METABASE_PVC_SIZE}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: metabase
    name: metabase
  spec:
    ports:
    - name: metabase-web
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: metabase
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: metabase
    name: metabase
  spec:
    host: metabase-${ENV_NAME}.apps.silver.devops.gov.bc.ca
    path: /
    port:
      targetPort: metabase-web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: metabase
      weight: 100
    wildcardPolicy: None
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: metabase
    name: metabase
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: metabase
      deploymentconfig: metabase
    strategy:
      activeDeadlineSeconds: 600
      recreateParams:
        timeoutSeconds: 300
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: metabase
          deploymentconfig: metabase
      spec:
        containers:
        - name: metabase
          image:
          imagePullPolicy: Always
          env:
            - name: MB_DB_FILE
              value: /tmp/metabase.db
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /metabase-data
            name: metabase-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: metabase
        serviceAccountName: metabase
        terminationGracePeriodSeconds: 30
        volumes:
        - name: metabase-data
          persistentVolumeClaim:
            claimName: metabase
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - metabase
        from:
          kind: ImageStreamTag
          name: metabase:v0.41.5
          namespace: ac294c-tools
        lastTriggeredImage: 
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
