apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: superset-bc
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the superset image
      creationTimestamp: null
      name: superset
    spec:
      lookupPolicy:
        local: false
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: superset
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: superset:20211213
          namespace: ac294c-tools
      postCommit: {}
      resources: 
        limits:
          cpu: '1'
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 250Mi        
      runPolicy: Serial
      source:
        contextDir: openshift/templates/superset/superset
        git:
          ref: superset2-0.1.0
          uri: https://github.com/bcgov/cthub.git
        type: Git
      strategy:
        dockerStrategy:
          forcePull: true
          noCache: true
          pullSecret:
            name: artifacts-pull-default-idxprm
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers: []
    status:
      lastVersion: 0
