apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: superset-dc
parameters:
  - name: ENV_NAME
    value: test
    required: true
  - name: CPU_REQUEST
    value: 200m
    displayName: Requested CPU
    description: Requested CPU
    required: true    
  - name: CPU_LIMIT
    value: 400m
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    value: 700Mi
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    value: 1400Mi
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: REPLICAS
    description: |
      The number of replicas to use.
    displayName: REPLICAS
    value: "1"    
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: superset
    name: superset
  spec:
    ports:
    - name: superset-web
      port: 8088
      protocol: TCP
      targetPort: 8088
    selector:
      app: superset
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      cluster-name: patroni-${ENV_NAME}
    name: patroni-master-${ENV_NAME}-superset
  spec:
    ports:
      - port: 5432
        protocol: TCP
        targetPort: 5432
    selector:
      cluster-name: patroni-${ENV_NAME}
      role: master
      app.kubernetes.io/name: patroni
    sessionAffinity: None
    type: ClusterIP
  status:    
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: superset
    name: superset
  spec:
    host: superset-${ENV_NAME}.apps.silver.devops.gov.bc.ca
    path: /
    port:
      targetPort: superset-web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: superset
      weight: 100
    wildcardPolicy: None
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: superset-home
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-file-standard
      template.openshift.io.bcgov/create: 'true'
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 2Gi        
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: superset
    name: superset
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 10
    test: false
    selector:
      app: superset
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: superset
      spec:
        volumes:
          - name: superset-home
            persistentVolumeClaim:
              claimName: superset-home
        containers:
          - name: superset-app-gunicorn
            image: >-
              image-registry.openshift-image-registry.svc:5000/ac294c-tools/superset:20211213
            ports:
              - containerPort: 8088
                protocol: TCP
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUEST}
                memory: ${MEMORY_REQUEST}                
            env:
              - name: COMPOSE_PROJECT_NAME
                value: superset
              - name: DATABASE_DB
                valueFrom:
                  secretKeyRef:
                    key: superset-db-name
                    name: patroni-creds-${ENV_NAME}
              - name: DATABASE_HOST
                value: patroni-master-test
              - name: DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    key: superset-db-username
                    name: patroni-creds-${ENV_NAME}
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: superset-db-password
                    name: patroni-creds-${ENV_NAME}
              - name: DATABASE_PORT
                value: '5432'
              - name: DATABASE_DIALECT
                value: postgresql
              - name: PYTHONPATH
                value: '/app/pythonpath:/app/docker/pythonpath_dev'
              - name: REDIS_HOST
                value: redis
              - name: REDIS_PORT
                value: '6379'
              - name: FLASK_ENV
                value: production
              - name: SUPERSET_ENV
                value: production
              - name: SUPERSET_LOAD_EXAMPLES
                value: 'no'
              - name: CYPRESS_CONFIG
                value: 'false'
              - name: SUPERSET_PORT
                value: '8088'
            volumeMounts:
              - name: superset-home
                mountPath: /app/superset_home
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler    
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
