apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-backend-bc
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is itvr
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName:
    description:  image tag name for output
    required: true
  - name: GIT_URL
    displayName:
    description: itvr repo
    required: true
  - name: GIT_REF
    displayName:
    description: itvr branch name of the pr
    required: true
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        description: Keeps track of changes in the backend image
      labels:
        shared: "true"
      creationTimestamp: null
      name: ${NAME}-backend
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        description: Defines how to build the application
      creationTimestamp: null
      name: ${NAME}-backend${SUFFIX}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-backend:${VERSION}
      postCommit: {}
      resources:
        limits:
          cpu: 300m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 200Mi
      runPolicy: SerialLatestOnly
      source:
        contextDir: django
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: ARTIFACTORY_USER
              valueFrom:
                secretKeyRef:
                  name: artifacts-default-pwpgbz
                  key: username
            - name: ARTIFACTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: artifacts-default-pwpgbz
                  key: password         
            - name: UPGRADE_PIP_TO_LATEST
              value: 'true'
            - name: DISABLE_COLLECTSTATIC
              value: 'true'
          from:
            kind: ImageStreamTag
            name: python-39:1-18.1634036280
          forcePull: true
          noCache: true            
        type: Source
      triggers:
      - imageChange: {}
        type: ImageChange
      - type: ConfigChange
    status:
      lastVersion: 0