FROM registry.access.redhat.com/ubi9/python-311:1-41

USER root

RUN rm /etc/rhsm-host

# Install some packages and clean up
RUN INSTALL_PKGS="libnghttp2.x86_64" && \
    dnf repolist --disablerepo='*' && \
    dnf upgrade -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    dnf -y clean all --enablerepo='*'

RUN dnf list | grep libnghttp2

USER 1001