FROM registry.access.redhat.com/ubi9/python-311:1-41

USER root

RUN subscription-manager status || true

RUN subscription-manager register || true 

RUN subscription-manager attach --auto || true

RUN yum clean all && \
    yum makecache

RUN yum upgrade libnghttp2.x86_64

USER 1001