apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: EMAIL_SERVICE_CLIENT_ID
  required: true
- name: EMAIL_SERVICE_CLIENT_SECRET
  required: true
- name: CHES_AUTH_URL
  required: true
- name: CHES_EMAIL_URL
  required: true
- name: SENDER_EMAIL
  required: true
- name: SENDER_NAME
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: itvr-email-service
  stringData:
    EMAIL_SERVICE_CLIENT_ID: ${EMAIL_SERVICE_CLIENT_ID}
    EMAIL_SERVICE_CLIENT_SECRET: ${EMAIL_SERVICE_CLIENT_SECRET}
    CHES_AUTH_URL: ${CHES_AUTH_URL}
    CHES_EMAIL_URL: ${CHES_EMAIL_URL}
    SENDER_EMAIL: ${SENDER_EMAIL}
    SENDER_NAME: ${SENDER_NAME}