apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: SUPERUSER_PASSWORD
  generate: expression
  from: '[a-z0-9]{8}'
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: itvr-superuser
  stringData:
    superuser-password: ${SUPERUSER_PASSWORD}