apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: NCDA_CLIENT_ID
  required: true
- name: NCDA_CLIENT_SECRET
  required: true
- name: NCDA_RESOURCE
  required: true
- name: NCDA_AUTH_URL
  required: true
- name: NCDA_SHAREPOINT_URL
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: itvr-ncda
  stringData:
    NCDA_CLIENT_ID: ${NCDA_CLIENT_ID}
    NCDA_CLIENT_SECRET: ${NCDA_CLIENT_SECRET}
    NCDA_RESOURCE: ${NCDA_RESOURCE}
    NCDA_AUTH_URL: ${NCDA_AUTH_URL}
    NCDA_SHAREPOINT_URL: ${NCDA_SHAREPOINT_URL}
