apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: APP_DB_USERNAME
  generate: expression
  from: itvr[a-z]{8}
- name: APP_DB_PASSWORD
  generate: expression
  from: '[a-z0-9]{16}'
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: itvr-patroni-app
  stringData:
    app-db-name: itvr
    app-db-username: ${APP_DB_USERNAME}
    app-db-password: ${APP_DB_PASSWORD}