apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: ACCESS_KEY_ID
  required: true
- name: SECRET_ACCESS_KEY
  required: true
- name: SERVER_URL
  required: true  
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: itvr-object-storage
  stringData:
    root-user: ${ACCESS_KEY_ID}
    root-password: ${SECRET_ACCESS_KEY}
    server-url: ${SERVER_URL}
