---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: backup-container
parameters:
  - name: NAME
    displayName: Name
    description: The suffix for all created objects
    required: false
    value: backup-container
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: backup-container
      creationTimestamp:
      labels:
        app: backup-container
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: backup-container
      creationTimestamp:
      labels:
        app: backup-container
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
      runPolicy: SerialLatestOnly
      source:
        type: Git
        contextDir: "openshift/templates/backup-container"
        git:
          uri: https://github.com/bcgov/itvr.git
          ref: backup-container-1.0.0
      strategy:
        dockerStrategy:
          pullSecret:
            name: artifacts-pull-default-pwpgbz
          forcePull: true
          noCache: true
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: backup-container:2.4.0
      resources: {}
      postCommit: {}
      nodeSelector:
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
