apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: metabase-dc
parameters:
  - name: ENV_NAME
    value: 
    required: true
  - name: SUFFIX
    displayName: null
    description: sample is -dev-97    
  - name: CPU_REQUEST
    value: 130m
    displayName: Requested CPU
    description: Requested CPU
    required: true    
  - name: CPU_LIMIT
    value: 260m
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    value: 820Mi
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    value: 1640Mi
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: REPLICAS
    description: |
      The number of replicas to use.
    displayName: REPLICAS
    value: "1"    
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: metabase
    labels:
      app: metabase
      service: metabase
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: metabase
    name: metabase
  spec:
    ports:
    - name: metabase-web
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: metabase
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: metabase
    name: metabase
  spec:
    host: metabase-${ENV_NAME}.apps.silver.devops.gov.bc.ca
    path: /
    port:
      targetPort: metabase-web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: metabase
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      cluster-name: patroni${SUFFIX}
    name: patroni-master${SUFFIX}-metabase
  spec:
    ports:
      - port: 5432
        protocol: TCP
        targetPort: 5432
    selector:
      cluster-name: patroni${SUFFIX}
      role: master
      app.kubernetes.io/name: patroni
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}    
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: metabase
    name: metabase
  spec:
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 10
    selector:
      app: metabase
      deploymentconfig: metabase
    strategy:
      activeDeadlineSeconds: 600
      recreateParams:
        timeoutSeconds: 300
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: metabase
          deploymentconfig: metabase
      spec:
        containers:
        - name: metabase
          image:
          imagePullPolicy: Always
          env:
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  key: metabase-db-name
                  name: patroni-creds-${ENV_NAME}
            - name: MB_DB_PORT
              value: '5432'
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  key: metabase-db-username
                  name: patroni-creds-${ENV_NAME}
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: metabase-db-password
                  name: patroni-creds-${ENV_NAME}
            - name: MB_DB_HOST
              value: patroni-master${SUFFIX}-metabase
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            readinessProbe:
              httpGet:
                path: /api/health
                port: 3000
                scheme: HTTP
              initialDelaySeconds: 180
              timeoutSeconds: 5
              periodSeconds: 30
              successThreshold: 1
              failureThreshold: 10              
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: metabase
        serviceAccountName: metabase
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - metabase
        from:
          kind: ImageStreamTag
          name: metabase:v0.41.1
          namespace: ac294c-tools
        lastTriggeredImage: 
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
