apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: metabase-bc
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the metabase image
    creationTimestamp: null
    name: metabase
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: metabase
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: metabase:v0.41.5
        namespace: ac294c-tools
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: openshift/templates/metabase
      git:
        ref: release-0.2.0
        uri: https://github.com/bcgov/cthub.git
      type: Git
    strategy:
      dockerStrategy:
        forcePull: true
        noCache: true
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
  status:
    lastVersion: 0
