# Default values for itvr-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 60m
    memory: 60Mi
  requests:
    cpu: 30m
    memory: 30Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

frontend:
  reactAppBCSCKeycloakClientId: itvr
  reactAppBCSCKeycloakRealm: zelda
  reactAppBCSCKeycloakUrl: https://loginproxy.gov.bc.ca/auth/
  reactAppApiBase: https://itvr-backend-prod.apps.silver.devops.gov.bc.ca
  reactAppBCeIDKeycloakClientId: itvr-on-gold-cluster-3972
  reactAppBCeIDKeycloakRealm: standard
  reactAppBCeIDKeycloakUrl: https://loginproxy.gov.bc.ca/auth/
  snowplowCollector: "spt.apps.gov.bc.ca"
  createFrontendRoute: false


