apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: frontend
parameters:
  - name: NAME
    displayName:
    description: the module name entered when run yo bcdk:pipeline, which is zeva
    required: true
  - name: SUFFIX
    displayName:
    description: sample is -pr-0
    required: true
  - name: VERSION
    displayName:
    description:  image tag name for output
    required: true
  - name: GIT_URL
    displayName:
    description: itvr repo
    required: true
  - name: GIT_REF
    displayName:
    description: itvr branch name of the pr
    required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the client / front end image
    labels:
      shared: "true"
    creationTimestamp: null
    generation: 643
    name: ${NAME}-frontend
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-frontend${SUFFIX}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-frontend:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URL}
      type: Git
      contextDir: frontend
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs-16:1-18
          namespace: ac294c-tools
        forcePull: true
        noCache: true      
        env:
          - name: ARTIFACTORY_USER
            valueFrom:
              secretKeyRef:
                name: artifacts-default-pwpgbz
                key: username
          - name: ARTIFACTORY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: artifacts-default-pwpgbz
                key: password        
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
  status:
    lastVersion: 0