apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-keycloak-secret
parameters:
  - name: BCSC_KEYCLOAK_CLIENT_ID
    description: kyecloak client id for BCSC
    required: true
  - name: BCSC_KEYCLOAK_REALM
    description: realm for BCSC
    required: true
  - name: BCSC_KEYCLOAK_URL
    description: keycloak url for BCSC, the url needs ending /
    required: true
  - name: BCEID_KEYCLOAK_CLIENT_ID
    description: kyecloak client id for BCEID
    required: true
  - name: BCEID_KEYCLOAK_REALM
    description: realm for BCEID
    required: true
  - name: BCEID_KEYCLOAK_URL
    description: keycloak url for BCEID, the url needs ending /
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: itvr-keycloak
      labels: {}
    stringData:
      BCSC_KEYCLOAK_CLIENT_ID: "${BCSC_KEYCLOAK_CLIENT_ID}"
      BCSC_KEYCLOAK_REALM: "${BCSC_KEYCLOAK_REALM}"
      BCSC_KEYCLOAK_URL: "${BCSC_KEYCLOAK_URL}"
      BCEID_KEYCLOAK_CLIENT_ID: "${BCEID_KEYCLOAK_CLIENT_ID}"
      BCEID_KEYCLOAK_REALM: "${BCEID_KEYCLOAK_REALM}"
      BCEID_KEYCLOAK_URL: "${BCEID_KEYCLOAK_URL}"
