apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: itvr-keycloak-secret
parameters:
  - name: KEYCLOAK_CLIENT_ID
    description: kyecloak client id
    required: true
  - name: KEYCLOAK_REALM
    description: realm
    required: true
  - name: KEYCLOAK_URL
    description: keycloak url, the url needs ending /
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: itvr-keycloak
      labels: {}
    stringData:
      KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
      KEYCLOAK_URL: "${KEYCLOAK_URL}"
