## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: helm-build

on:
  workflow_dispatch:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  ## Also remember to update the version in .pipeline/lib/config.js
  PR_NUMBER: 497
  VERSION: 1.17.0
  GIT_URL: https://github.com/bcgov/itvr.git 
  TOOLS_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  DEV_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
  TEST_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
  PROD_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:

  ## This is the CI job
  build:

    name: Build ITVR on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env: 
      SUFFIXSS: -build-${{ env.PR_NUMBER }}
    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.TOOLS_NAMESPACE }}

      - name: Build ITVR Backend
        run: |
          cd openshift/templates/backend
          oc process -f ./backend-bc.yaml NAME=itvr SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
          oc cancel-build bc/itvr-backend-build-${{ inputs.pr-number }}
          oc start-build --wait=true itvr-backend-build-${{ inputs.pr-number }}

      - name: Build ITVR Frontend
        run: |
          cd openshift/templates/frontend
          oc process -f ./frontend-bc-docker.yaml NAME=itvr SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
          oc cancel-build bc/itvr-frontend-build-${{ inputs.pr-number }}
          oc start-build --wait=true itvr-frontend-build-${{ inputs.pr-number }}

      - name: Build ITVR Taskq
        run: |
          cd openshift/templates/task-queue
          oc process -f ./task-queue-bc.yaml NAME=itvr SUFFIX=-build-${{ env.PR_NUMBER }} VERSION=build-${{ env.VERSION }}-${{ env.PR_NUMBER }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ env.PR_NUMBER }}/head | oc apply --wait=true -f - -n ${{ env.TOOLS_NAMESPACE }}
          oc cancel-build bc/itvr-task-queue-build-${{ inputs.pr-number }}
          oc start-build --wait=true itvr-task-queue-build-${{ inputs.pr-number }}

