name: PR Build Template

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      build-suffix:
        required: true
        type: string
      build-image-tag-name:
        required: true
        type: string
    secrets:
      tools-namespace:
        required: true
      openshift-server:
        required: true
      openshift-token:
        required: true

env:
  GIT_URL: https://github.com/bcgov/itvr.git

jobs:
  build-backend:
    name: Build itvr backend on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr-number }}/head

      - name: Log in to Openshift
        # uses: redhat-actions/oc-login@v1.3
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.openshift-server }}
          openshift_token: ${{ secrets.openshift-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.tools-namespace }}

      - name: Build itvr Backend
        run: |
          cd openshift/templates/backend
          oc process -f ./backend-bc.yaml NAME=itvr SUFFIX=${{ inputs.build-suffix }} VERSION=${{ inputs.build-image-tag-name }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ inputs.pr-number }}/head | oc apply --wait=true -f - -n ${{ secrets.tools-namespace }}
          oc cancel-build bc/itvr-backend${{ inputs.build-suffix }}
          oc start-build --wait=true itvr-backend${{ inputs.build-suffix }}

  build-frontend:
    name: Build itvr frontend on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr-number }}/head

      - name: Log in to Openshift
        # uses: redhat-actions/oc-login@v1.3
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.openshift-server }}
          openshift_token: ${{ secrets.openshift-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.tools-namespace }}

      - name: Build itvr Frontend
        run: |
          cd openshift/templates/frontend
          oc process -f ./frontend-bc-docker.yaml NAME=itvr SUFFIX=${{ inputs.build-suffix }} VERSION=${{ inputs.build-image-tag-name }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ inputs.pr-number }}/head | oc apply --wait=true -f - -n ${{ secrets.tools-namespace }}
          oc cancel-build bc/itvr-frontend${{ inputs.build-suffix }}
          oc start-build --wait=true itvr-frontend${{ inputs.build-suffix }}

  build-task-queue:
    name: Build itvr task queue on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr-number }}/head

      - name: Log in to Openshift
        # uses: redhat-actions/oc-login@v1.3
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.openshift-server }}
          openshift_token: ${{ secrets.openshift-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.tools-namespace }}

      - name: Build itvr task queue
        run: |
          cd openshift/templates/task-queue
          oc process -f ./task-queue-bc.yaml NAME=itvr SUFFIX=${{ inputs.build-suffix }} VERSION=${{ inputs.build-image-tag-name }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ inputs.pr-number }}/head | oc apply --wait=true -f - -n ${{ secrets.tools-namespace }}
          oc cancel-build bc/itvr-task-queue${{ inputs.build-suffix }}
          oc start-build --wait=true itvr-task-queue${{ inputs.build-suffix }}

  build-cra:
    name: Build itvr cra on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.pr-number }}/head

      - name: Log in to Openshift
        # uses: redhat-actions/oc-login@v1.3
        uses: smlgbl/oc-login@main
        with:
          openshift_server_url: ${{ secrets.openshift-server }}
          openshift_token: ${{ secrets.openshift-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.tools-namespace }}

      - name: Build itvr cra
        run: |
          cd openshift/templates/cra
          oc process -f ./cra-bc-docker.yaml NAME=itvr SUFFIX=${{ inputs.build-suffix }} VERSION=${{ inputs.build-image-tag-name }} GIT_URL=${{ env.GIT_URL }} GIT_REF=refs/pull/${{ inputs.pr-number }}/head | oc apply --wait=true -f - -n ${{ secrets.tools-namespace }}
          oc cancel-build bc/itvr-cra${{ inputs.build-suffix }}
          oc start-build --wait=true itvr-cra${{ inputs.build-suffix }}
