# Please refer to ./readme.md for how to build single pull request

# Update this workflow name per pull request
name: PR Build on Dev

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
    branches:
          - 'release-*'
  
jobs:

  # call-unit-test:
  #   uses: ./.github/workflows/unit-test-template.yaml
  #   with:
  #     pr-number: ${{ github.event.pull_request.number }}

  call-pr-build:
    if: endsWith( github.event.pull_request.title, 'build-on-dev' )
    # needs: call-unit-test
    uses: ./.github/workflows/pr-build-template.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
      suffix: -dev-${{ github.event.pull_request.number }}
      build-image-tag-name: build-${{ github.event.pull_request.base.ref }}-${{ github.event.pull_request.number }}
      dev-image-tag-name: dev-${{ github.event.pull_request.base.ref }}-${{ github.event.pull_request.number }}
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      dev-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
      itvr-dev-username: ${{ secrets.ITVR_DEV_USERNAME }}
      itvr-dev-password: ${{ secrets.ITVR_DEV_PASSWORD }}
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
