name: PR Dev Database Template

on:
  workflow_call:
    inputs:
      pr-number:
        required: true
        type: string
      dev-suffix:
        required: true
        type: string        
    secrets:
      dev-namespace:
        required: true
      itvr-dev-username:
        required: true
      itvr-dev-password:
        required: true       
      openshift-server:
         required: true 
      openshift-token:   
         required: true       
  
jobs:

  database:

    name: Start Database
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ inputs.pr-number }}/head

      - name: Log in to Openshift
        uses: redhat-actions/oc-login@v1.2
        with:
          openshift_server_url: ${{ secrets.openshift-server }}
          openshift_token: ${{ secrets.openshift-token }}
          insecure_skip_tls_verify: true
          namespace: ${{ secrets.dev-namespace }}    

      - name: Setup Database
        shell: bash {0}
        run: |
          cd chart/itvr-spilo
          helm dependency build
          helm status -n ${{ secrets.dev-namespace }} itvr-spilo${{ inputs.dev-suffix }}
          if [ $? -eq 0 ]; then
            echo "itvr-spilo${{ inputs.dev-suffix }} exists already"
          else
            echo "Installing itvr-spilo${{ inputs.dev-suffix }}"
            helm install -n ${{ secrets.dev-namespace }} -f ./values-dev-pr.yaml --wait itvr-spilo${{ inputs.dev-suffix }} .
            oc -n ${{ secrets.dev-namespace }} wait --for=condition=Ready pod/itvr-spilo${{ inputs.dev-suffix }}-0
            oc -n ${{ secrets.dev-namespace }} exec itvr-spilo${{ inputs.dev-suffix }}-0 -- psql -c "create user ${{ secrets.itvr-dev-username }} WITH PASSWORD '${{ secrets.itvr-dev-password }}'" || true
            oc -n ${{ secrets.dev-namespace }} exec itvr-spilo${{ inputs.dev-suffix }}-0 -- psql -c "create database itvr owner ${{ secrets.itvr-dev-username }} ENCODING 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8'" || true
          fi

