## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: Deploy release to dev and test

on:
  workflow_dispatch:
  pull_request:
    types: [opened,edited,synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:

  call-pr-dev-database-template:
    if: startsWith( github.event.pull_request.title, 'Tracking pull request' )
    uses: ./.github/workflows/pr-dev-database-template.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
      dev-suffix: -dev
    secrets:
      dev-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
      itvr-dev-username: ${{ secrets.ITVR_DEV_USERNAME }}
      itvr-dev-password: ${{ secrets.ITVR_DEV_PASSWORD }}
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  # build-release:
  #   if: startsWith( github.event.pull_request.title, 'Tracking pull request' )
  #   name: Build release
  #   uses: ./.github/workflows/pr-build-template.yaml
  #   with:
  #     pr-number: ${{ github.event.pull_request.number }}
  #     build-suffix: -build-${{ github.event.pull_request.number }}
  #     build-image-tag-name: build-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}
  #   secrets:
  #     tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  #     openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
  #     openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  approval-deploy-on-dev:
    name: Approval the deployment on Dev
    needs: call-pr-dev-database-template
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Ask for approval for ITVR Dev deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: AlexZorkin,emi-hi,tim738745,kuanfandevops,jig-patel
          minimum-approvals: 1
          issue-title: "ITVR ${{ github.event.pull_request.head.ref }} Dev Deployment"

  deploy-on-dev: 
    name: Deploy on Dev
    needs: approval-deploy-on-dev
    uses: ./.github/workflows/pr-deploy-template.yaml
    with:
      pr-number: ${{ github.event.pull_request.number }}
      suffix: -dev
      build-image-tag-name: build-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}
      image-tag-name: dev-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}
      env-name: dev
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-dev
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
  
  # approval-deploy-on-test:
  #   name: Approval the deployment on Test
  #   needs: deploy-on-dev
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 240
  #   steps:
  #     - name: Ask for approval for ITVR Test deployment
  #       uses: trstringer/manual-approval@v1.6.0
  #       with:
  #         secret: ${{ github.TOKEN }}
  #         approvers: AlexZorkin,emi-hi,tim738745,kuanfandevops,jig-patel
  #         minimum-approvals: 1
  #         issue-title: "ITVR $VERSION Test Deployment"
  #         timeout-minutes: 240

  # deploy-on-test:
  #   needs: approval-deploy-on-test
  #   uses: ./.github/workflows/pr-deploy-template.yaml
  #   with:
  #     pr-number: $PR_NUMBER
  #     suffix: -test
  #     build-image-tag-name: build-$VERSION-$PR_NUMBER
  #     image-tag-name: test-$VERSION-$PR_NUMBER
  #     env-name: test
  #   secrets:
  #     tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
  #     namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
  #     openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
  #     openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}