name: ITVR release-1.27.0

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: "Tracking pull request number"
        required: true
        default: 703
      release_branch:
        description: "The name of the release branch"
        required: true
        default: release-1.27.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build release
    uses: ./.github/workflows/pr-build-template.yaml
    with:
      pr-number: ${{ github.event.inputs.pull_request }}
      build-suffix: -build-${{ github.event.inputs.pull_request }}
      build-image-tag-name: build-${{ github.event.inputs.release_branch }}-${{ github.event.inputs.pull_request }}
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  approval-deploy-on-test:
    name: Approval the deployment on Test
    needs: build-release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Ask for approval for ITVR Test deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: emi-hi,tim738745,kuanfandevops,JulianForeman
          minimum-approvals: 1
          issue-title: "ITVR ${{ github.event.inputs.release_branch }} Test Deployment"

  deploy-on-test:
    name: Deploy on Test
    needs: approval-deploy-on-test
    uses: ./.github/workflows/pr-deploy-template.yaml
    with:
      pr-number: ${{ github.event.inputs.pull_request }}
      suffix: -test
      build-image-tag-name: build-${{ github.event.inputs.release_branch }}-${{ github.event.inputs.pull_request }}
      image-tag-name: test-${{ github.event.inputs.release_branch }}-${{ github.event.inputs.pull_request }}
      env-name: test
      frontend-route-host-name: itvr-test.apps.silver.devops.gov.bc.ca
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  approval-deploy-on-prod:
    name: Approval the deployment on Prod
    needs: deploy-on-test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Ask for approval for ITVR Prod deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: emi-hi,tim738745,kuanfandevops,JulianForeman
          minimum-approvals: 2
          issue-title: "ITVR ${{ github.event.inputs.release_branch }} Prod Deployment"

  deploy-on-prod:
    name: Deploy on Prod
    needs: approval-deploy-on-prod
    uses: ./.github/workflows/pr-deploy-template.yaml
    with:
      pr-number: ${{ github.event.inputs.pull_request }}
      suffix: -prod
      build-image-tag-name: build-${{ github.event.inputs.release_branch }}-${{ github.event.inputs.pull_request }}
      image-tag-name: prod-${{ github.event.inputs.release_branch }}-${{ github.event.inputs.pull_request }}
      env-name: prod
      frontend-route-host-name: electric-vehicle-rebates.gov.bc.ca
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
