## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: ITVR release-1.18.0 (HELM)

on:
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  PR_NUMBER: 545
  VERSION: 1.18.0
  RELEASE_BRANCH: release-1.18.0
  GIT_URL: https://github.com/bcgov/itvr.git 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:

  build-release:
    name: Build release
    uses: ./.github/workflows/pr-build-template.yaml
    with:
      pr-number: ${{ env.PR_NUMBER }}
      build-suffix: -build-${{ env.PR_NUMBER }}
      build-image-tag-name: build-${{ env.RELEASE_BRANCH }}-${{ env.PR_NUMBER }}
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

 
  approval-deploy-on-test:
    name: Approval the deployment on Test
    needs: build-release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Ask for approval for ITVR Test deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: AlexZorkin,emi-hi,tim738745,kuanfandevops,jig-patel,prv-proton
          minimum-approvals: 1
          issue-title: "ITVR ${{ env.RELEASE_BRANCH }} Test Deployment"

  deploy-on-test: 
    name: Deploy on Test
    needs: approval-deploy-on-test
    uses: ./.github/workflows/pr-deploy-template.yaml
    with:
      pr-number: ${{ env.PR_NUMBER }}
      suffix: -test
      build-image-tag-name: build-${{ env.RELEASE_BRANCH }}-${{ env.PR_NUMBER }}
      image-tag-name: test-${{ env.RELEASE_BRANCH }}-${{ env.PR_NUMBER }}
      env-name: test
      frontend-route-host-name: itvr-test.apps.silver.devops.gov.bc.ca
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-test
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}

  approval-deploy-on-prod:
    name: Approval the deployment on Prod
    needs: deploy-on-test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Ask for approval for ITVR Prod deployment
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: AlexZorkin,emi-hi,tim738745,kuanfandevops,jig-patel
          minimum-approvals: 2
          issue-title: "ITVR ${{ env.RELEASE_BRANCH }} Prod Deployment"

  deploy-on-prod: 
    name: Deploy on Prod
    needs: approval-deploy-on-prod
    uses: ./.github/workflows/pr-deploy-template.yaml
    with:
      pr-number: ${{ env.PR_NUMBER }}
      suffix: -prod
      build-image-tag-name: build-${{ env.RELEASE_BRANCH }}-${{ env.PR_NUMBER }}
      image-tag-name: prod-${{ env.RELEASE_BRANCH }}-${{ env.PR_NUMBER }}
      env-name: prod
      frontend-route-host-name: electric-vehicle-rebates.gov.bc.ca
    secrets:
      tools-namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-tools
      namespace: ${{ secrets.OPENSHIFT_NAMESPACE_PLATE }}-prod
      openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift-token: ${{ secrets.OPENSHIFT_TOKEN }}
