## For each release, the value of workflow name, branches and PR_NUMBER need to be adjusted accordingly

name: CI/CD ITVR GHA-django-unit-test-1.11.0

on:
  push:
    branches: [ GHA-django-unit-test-1.11.0 ]
  workflow_dispatch:
  workflow_call:

env:
  ## The pull request number of the Tracking pull request to merge the release branch to main
  ## Also remember to update the version in .pipeline/lib/config.js
  PR_NUMBER: 311
  RELEASE_NAME: GHA-django-unit-test-1.11.0

jobs:

  ## This is the CI job
  build:

    name: Build ITVR on Openshift
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:

      ## it will checkout to /home/runner/work/itvr/itvr
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Django Test CI
        env:
          GITHUB_WORKSPACE: "/home/runner/work/itvr/itvr"
        uses: kuanfandevops/django-test-action@v0.3
        with:
          settings-dir-path: "django/api"
          requirements-file: "django/requirements.txt"

