name: ZAP Full Scan
on:
  workflow_dispatch:
jobs:

  approval-zap-full-scan:
    name: Approve the ZAP Full Scan on Test URLS
    runs-on: ubuntu-latest
    timeout-minutes: 60 
    steps:
      - name: Ask for approval for Zap Full Scan
        uses: trstringer/manual-approval@v1.6.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: emi-hi,tim738745,kuanfandevops,JulianForeman
          minimum-approvals: 1
          issue-title: "Please communicate with Platform Team for Zap Full Scan for the ITVR Test URLs and approve this request"

  zap-full-scan:
    runs-on: ubuntu-latest
    needs: approval-zap-full-scan
    steps:
      - name: ZAP Full Scan on Frontend
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'https://itvr-test.apps.silver.devops.gov.bc.ca'
          issue_title: ZAP Test Frontend Baseline Scan Report
      - name: ZAP Full Scan on Backend
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'https://itvr-test-backend.apps.silver.devops.gov.bc.ca'
          issue_title: ZAP Test Backend Baseline Scan Report