name: ZAP Baseline Scan
on:
  workflow_dispatch:
    inputs:
      envname:
        description: 'dev or test'
        required: true
        default: dev
jobs:

  zap-baseline-scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan on Frontend
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: "https://itvr-${{ github.event.inputs.envname }}.apps.silver.devops.gov.bc.ca"
          issue_title: "ZAP ${{ github.event.inputs.envname }} Frontend Baseline Scan Report"
      - name: ZAP Baseline Scan on Backend
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'https://itvr-${{ github.event.inputs.envname }}-backend.apps.silver.devops.gov.bc.ca'
          issue_title: "ZAP ${{ github.event.inputs.envname }} Backend Baseline Scan Report"