apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: redis-dc
parameters:
  - name: ENV_NAME
    value: test
    required: true
  - name: CPU_REQUEST
    value: 50M
    displayName: Requested CPU
    description: Requested CPU
    required: true    
  - name: CPU_LIMIT
    value: 200M
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    value: 50M
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    value: 500M
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
  - name: REPLICAS
    description: |
      The number of replicas to use.
    displayName: REPLICAS
    value: "1"    
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: redis
    name: redis
  spec:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: redis
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-block-standard
      template.openshift.io.bcgov/create: 'true'
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: redis
    name: redis
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: redis
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: redis
      spec:
        volumes:
          - name: redis
            persistentVolumeClaim:
              claimName: redis
        containers:
          - name: redis
            image: >-
              image-registry.openshift-image-registry.svc:5000/ac294c-tools/redis:6.2.6
            ports:
              - containerPort: 6379
                protocol: TCP
            resources: {}
            volumeMounts:
              - name: redis
                mountPath: /data
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler    
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
